[project]
name = 'education-certification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.education-certification]
path = 'contracts/education-certification.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
